### ISSUE TITLE
Have you tested performance of DETR and SMCA on coco?

### ISSUE THREAD

**Issue by bamps53** [EmGarr/kerod#3]
If so, is there any chance to get pretrained model?
And as for SMCA, which part is different from original implementation?

**Comment by EmGarr** [comment]
I don't have access to GPUs currently so I cannot really test Detr or SMCA. However, Kerod implementation has been tested against the facebook one and regarding the similarity matching and the loss are exactly the same. What I mean by that is that for the same y_pred and the same groundtruths Facebook implementation and Kerod will have exactly the same losses.

For SMCA, I just received the code from the author I'll fix the dissimilarities asap. 

The thing that is currently missing is the random crop data augmentation.

**Comment by bamps53** [comment]
Oh you already have official SMCA implement!
And random crop is not so important part:)
Thanks for the answer.
